language: python
python: "2.7"
before_install:
  - npm install -g jshint
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/test --all
  - bin/code-analysis
after_success:
 - bin/test-coverage
